# $\bm{4}$ $\enspace$ **数据操作 + 数据预处理**

## $\bm{4.1}$ $\enspace$ **数据操作**

### $\bm{4.1.1}$ $\enspace$ **入门**

首先，我们导入 `torch`。请注意，虽然它被称为PyTorch，但我们应该导入 `torch` 而不是 `pytorch`

In [79]:
import torch

张量表示由一个数值组成的数组，这个数组可能有多个维度

In [80]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

可以通过张量的 `shape` 属性来访问张量的形状和张量中元素的总数

In [81]:
x.shape

torch.Size([12])

In [82]:
x.numel()

12

要改变一个张量的形状而不改变元素数量和元素值，可以调用 `reshape` 函数

In [83]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

使用全 $0$、全 $1$、其他常量或者从特定分布中随机采样的数字

In [84]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [85]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [86]:
torch.randn((2, 3, 4))

tensor([[[-0.2168, -0.8392, -0.1133, -0.9239],
         [ 0.0824, -0.5508,  0.3942,  0.0325],
         [ 0.1123,  0.4008,  0.1790, -0.2086]],

        [[-0.6837,  0.7412, -1.2714,  0.5984],
         [ 0.9489,  1.8854, -0.1004, -0.6553],
         [-1.8470,  0.9173, -0.2316,  1.3200]]])

通过提供包含数值的 Python 列表（或嵌套列表）来为所需张量中的每个元素赋予确定值

In [87]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### $\bm{4.1.2}$ $\enspace$ **运算符**

常见的标准算术运算符（`+`、`-`、`*`、`/` 和 `**`）都可以被升级为按元素运算

In [88]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

按元素方式应用更多的计算

In [89]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

我们也可以把多个张量连结 (concatenate) 在一起

In [90]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

通过 *逻辑运算符* 构建二元张量

In [91]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量中的所有元素进行求和会产生一个只有一个元素的张量

In [92]:
X.sum()

tensor(66.)

### $\bm{4.1.3}$ $\enspace$ **广播机制**

即使形状不同，我们仍然可以通过调用 *广播机制* (broadcasting mechanism) 来执行按元素操作

In [93]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [94]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### $\bm{4.1.4}$ $\enspace$ **索引和切片**

可以用 `[-1]` 选择最后一个元素，可以用 `[1:3]` 选择第二个和第三个元素

In [95]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

除读取外，我们还可以通过指定索引来将元素写入矩阵

In [96]:
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值

In [97]:
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### $\bm{4.1.5}$ $\enspace$ **节省内存**

运行一些操作可能会导致为新结果分配内存

In [98]:
before = id(Y)
Y = Y + X
id(Y) == before

False

执行原地操作

In [99]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2325472081856
id(Z): 2325472081856


如果在后续计算中没有重复使用 `X`，我们也可以使用 `X[:] = X + Y` 或 `X += Y` 来减少操作的内存开销

In [100]:
before = id(X)
X += Y
id(X) == before

True

### $\bm{4.1.6}$ $\enspace$ **转换为其他 Python 对象**

转换为 NumPy 张量

In [101]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

将大小为 $1$ 的张量转换为 Python 标量

In [102]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

### $\bm{4.1.7}$ $\enspace$ **练习**

$1$. $ \ $ 运行本节中的代码。将本节中的条件语句 `X == Y` 更改为 `X < Y` 或 `X > Y`，然后看看你可以得到什么样的张量

In [103]:
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X < Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [104]:
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

$2$. $ \ $ 用其他形状（例如三维张量）替换广播机制中按元素操作的两个张量。结果是否与预期相同？

In [105]:
import torch
a = torch.arange(3).reshape(1, 3, 1)
b = torch.arange(4).reshape(2, 1, 2)
a + b

tensor([[[0, 1],
         [1, 2],
         [2, 3]],

        [[2, 3],
         [3, 4],
         [4, 5]]])

In [106]:
(a + b).size()


torch.Size([2, 3, 2])

## $\bm{4.2}$ $\enspace$ **数据预处理**


### $\bm{4.2.1}$ $\enspace$ **读取数据集**

创建一个人工数据集，并存储在 csv（逗号分隔值）文件


In [107]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')


从创建的 csv 文件中加载原始数据集


In [108]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)


   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


### $\bm{4.2.2}$ $\enspace$ **处理缺失值**

为了处理缺失的数据，典型的方法包括*插值*和*删除*，这里，我们将考虑插值


In [109]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean(numeric_only=True))
print(inputs)


   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


对于 `inputs` 中的类别值或离散值，我们将“NaN”视为一个类别


In [110]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)


   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


### $\bm{4.2.3}$ $\enspace$ **转换为张量格式**

现在 `inputs` 和 `outputs` 中的所有条目都是数值类型，它们可以转换为张量格式


In [111]:
import torch

X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

### $\bm{4.2.4}$ $\enspace$ **习题**

$1$. $ \ $ 删除缺失值最多的行或列

In [112]:
key_dict = data.isna().sum().to_dict()
print(key_dict)
max_key = max(key_dict, key=key_dict.get)
del data[max_key]
print(data)




{'NumRooms': 2, 'Alley': 3, 'Price': 0}
   NumRooms   Price
0       NaN  127500
1       2.0  106000
2       4.0  178100
3       NaN  140000


$2$. $ \ $ 将预处理后的数据集转换为张量格式

In [113]:
import torch
inputs, outputs = data.iloc[:, 0], data.iloc[:, 1]
X, Y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, Y

(tensor([nan, 2., 4., nan], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))